# Generated by Django 4.0.4 on 2022-11-06 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(default='do not use "/" in naming device', max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='VideoTorent',
            fields=[
                ('video_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(help_text='use upper case words', max_length=100)),
                ('year_released', models.CharField(blank=True, max_length=10, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Torent_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('torrent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.videotorent')),
            ],
        ),
        migrations.CreateModel(
            name='Frp_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.device')),
            ],
        ),
        migrations.CreateModel(
            name='Frp_bypass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('installation_guide', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.device')),
            ],
        ),
        migrations.CreateModel(
            name='Firmwares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('installation_guide', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.device')),
            ],
        ),
        migrations.CreateModel(
            name='Firm_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('d_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.device')),
            ],
        ),
        migrations.CreateModel(
            name='Cracked_tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('installation_guide', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.device')),
            ],
        ),
        migrations.CreateModel(
            name='Crack_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.device')),
            ],
        ),
    ]
