# Generated by Django 4.0.4 on 2022-11-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='user uppercase', max_length=50, primary_key=True, serialize=False),
        ),
    ]
